CREATE TABLE IF NOT EXISTS Produits (
    ref VARCHAR(100) PRIMARY KEY,
    cat VARCHAR(100) NOT NULL,
    nom VARCHAR(255) NOT NULL,
    marque VARCHAR(255) NOT NULL,
    prix DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
